"""
PDF export service for ATS Resume Screener.

Converts the HTML reports generated by report_generator.py
into a single PDF document.
"""

from io import BytesIO
from typing import Dict

from weasyprint import HTML


def generate_combined_pdf(html_docs: Dict[str, str]) -> bytes:
    """
    Convert the generated HTML reports into one PDF.

    Expected input:
        {
            "summary": "<html>...</html>",
            "skill_report": "<html>...</html>",
            "jd_report": "<html>...</html>"
        }

    Returns:
        PDF document as bytes.
    """

    if not html_docs:
        raise ValueError("No HTML reports were provided.")

    # Preserve the intended report order.
    report_order = [
        "summary",
        "skill_report",
        "jd_report",
    ]

    sections = []

    for key in report_order:
        html_content = html_docs.get(key)

        if not html_content:
            continue

        sections.append(
            f"""
            <section class="report-section">
                {html_content}
            </section>
            """
        )

    # Include any additional reports that may be added later.
    for key, html_content in html_docs.items():
        if key not in report_order and html_content:
            sections.append(
                f"""
                <section class="report-section">
                    {html_content}
                </section>
                """
            )

    if not sections:
        raise ValueError("The HTML reports are empty.")

    combined_html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">

        <style>
            @page {{
                size: A4;
                margin: 18mm 15mm 18mm 15mm;
            }}

            body {{
                font-family: Arial, Helvetica, sans-serif;
                font-size: 10.5pt;
                line-height: 1.45;
                color: #172033;
                background: white;
            }}

            .report-section {{
                page-break-after: always;
            }}

            .report-section:last-child {{
                page-break-after: auto;
            }}

            h1 {{
                font-size: 22pt;
                margin-bottom: 12px;
            }}

            h2 {{
                font-size: 16pt;
                margin-top: 16px;
                margin-bottom: 8px;
            }}

            h3 {{
                font-size: 13pt;
                margin-top: 12px;
                margin-bottom: 6px;
            }}

            p {{
                margin: 5px 0;
            }}

            ul, ol {{
                margin-top: 5px;
                margin-bottom: 8px;
            }}

            li {{
                margin-bottom: 3px;
            }}

            table {{
                width: 100%;
                border-collapse: collapse;
                margin: 10px 0;
            }}

            th, td {{
                border: 1px solid #d9dee8;
                padding: 6px 8px;
                vertical-align: top;
            }}

            th {{
                font-weight: bold;
                background: #f1f4f8;
            }}

            img {{
                max-width: 100%;
                height: auto;
            }}

            .page-break {{
                page-break-before: always;
            }}
        </style>
    </head>

    <body>
        {"".join(sections)}
    </body>
    </html>
    """

    pdf_buffer = BytesIO()

    HTML(
        string=combined_html,
        base_url=None,
    ).write_pdf(pdf_buffer)

    return pdf_buffer.getvalue()